apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoic2ltb2hpbGlsaTdAZ21haWwuY29tIiwicGFzc3dvcmQiOiJnaHBfMkJzbmMzb3JwbDNWb3hDNFEzM243RU5idW85NVY2MzQwTGtMIiwiYXV0aCI6ImMybHRiMmhwYkdsc2FUZEFaMjFoYVd3dVkyOXRPbWRvY0Y4eVFuTnVZek52Y25Cc00xWnZlRU0wVVRNemJqZEZUbUoxYnprMVZqWXpOREJNYTB3PSJ9fX0=
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
